#!/usr/bin/env bash

# Update package index
apt-get update

# Install Nginx
apt-get install -y nginx

# Configure Nginx
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
/usr/sbin/service nginx restart

