#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user and listen on port 8080
useradd nginx
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/cache/nginx
sed -i 's/^user\s\+.*$/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/^listen\s\+.*$/listen \*:8080 default_server;/' /etc/nginx/nginx.conf
service nginx start

