#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user and listen on port 8080
service nginx stop
# Modify the nginx user to have appropriate permissions
usermod -a -G adm nginx

# Change ownership of necessary directories to the nginx user
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/cache/nginx

# Modify the nginx.conf file to run nginx as the nginx user and listen on port 8080
sed -i '/^\s*user /s/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i '/^\s*listen /s/listen .*/listen 8080 default_server;/' /etc/nginx/nginx.conf

# Start the nginx service
service nginx start

