#!/usr/bin/env bash
# This script configures Nginx to proxy requests to the route /airbnb-dynamic/number_odd_or_even/(any integer)
# to a Gunicorn instance listening on port 5000

server {
    listen 80;
    server_name _;

    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /airbnb-dynamic/number_odd_or_even/ {
        proxy_pass http://127.0.0.1:5001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

